language: node_js
node_js:
  - 'lts/*'
cache: npm
script:
  - audit-ci --moderate
  - npm run license-report
  - npm run lint
  - npm run build
  - npm run test
  - npm run build:docs
  - npm run coveralls
deploy:
  - provider: npm
    email: 'support@lightelligence.io'
    api_key: $NPM_TOKEN_PUBLISH
    skip_cleanup: true
    on:
      tags: true
      branch: master
      repo: lightelligence-io/react

  - provider: pages
    local_dir: docs
    skip_cleanup: true
    github_token: $GITHUB_ACCESS_TOKEN
    target_branch: gh-pages
    on:
      branch: master
