language: node_js
node_js:
  - 'lts/*'
cache: npm
script:
  - audit-ci --moderate
  - npm run license-report
  - npm run lint
  - npm run build
  - npm run test
  - npm run build:docs
  - npm run coveralls

before_deploy:
  - git config --local user.name "lightelligence-bot"
  - git config --local user.email "support@lightelligence.io"
  - export TRAVIS_TAG=$(node -p "require('./package.json').version")
  - git tag $TRAVIS_TAG

deploy:

  - provider: releases
    api_key: $GITHUB_ACCESS_TOKEN
    on:
      branch: master
      repo: lightelligence-io/react
      condition: "$TRAVIS_COMMIT_MESSAGE =~ ^release*"

  - provider: npm
    email: 'support@lightelligence.io'
    api_key: $NPM_TOKEN_PUBLISH
    skip_cleanup: true
    on:
      branch: master
      repo: lightelligence-io/react
      condition: "$TRAVIS_COMMIT_MESSAGE =~ ^release*"

  - provider: pages
    local_dir: docs
    skip_cleanup: true
    github_token: $GITHUB_ACCESS_TOKEN
    target_branch: gh-pages
    on:
      branch: master
